#!/usr/bin/env bash

THIS="${BASH_SOURCE[0]}"
ROOT="$(dirname $THIS)/../"
cd $ROOT

PLACEHOLDER="heyproj"

grep -rlZ $PLACEHOLDER . | xargs -0 sed -i "s:$PLACEHOLDER:$1:g"
rm $THIS
rename "$PLACEHOLDER" "$1" $ROOT/scripts/*
